// docx parser -> IR tests. Proves the IR captures table cells (structure, text,
// addressing) and grades per-cell parser confidence on the awkward cases, per
// the decided docx confidence policy. Fixtures are the two synthetic .docx files
// under tests/fixtures (generated by generate.mjs).

import { test, expect, describe } from "vitest";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { parseDocx } from "../src/parsers/docx.js";
import type { IRTable, TableCellElement } from "../src/ir/types.js";

const loadFixture = (name: string) =>
  readFile(fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url)));

/** Look up the cell element covering a logical grid coordinate. */
function cellAt(table: IRTable, row: number, col: number): TableCellElement {
  const id = table.grid[row]?.[col];
  if (!id) throw new Error(`no cell at (${row}, ${col}) in ${table.id}`);
  const cell = table.cells.find((c) => c.id === id);
  if (!cell) throw new Error(`grid points at unknown cell ${id}`);
  return cell;
}
const textAt = (t: IRTable, r: number, c: number) => cellAt(t, r, c).text;

describe("basic score table fixture", () => {
  test("captures the 5-column score grid, cell by cell", async () => {
    const ir = await parseDocx(await loadFixture("basic-score-table.docx"));
    expect(ir.tables).toHaveLength(1);
    const t = ir.tables[0]!;

    expect(t.numColumns).toBe(5);
    expect(t.numRows).toBe(4);
    expect(t.confidence).toBe("parsed_ok");

    // Header row.
    expect([0, 1, 2, 3, 4].map((c) => textAt(t, 0, c))).toEqual([
      "Scale",
      "Score",
      "95% CI",
      "%ile",
      "Classification",
    ]);

    // A data row, including the en-dash CI and a numeric percentile.
    expect([0, 1, 2, 3, 4].map((c) => textAt(t, 1, c))).toEqual([
      "Verbal Comprehension",
      "108",
      "101–115",
      "70",
      "Average",
    ]);

    // A single interior cell resolves by (row, column) addressing.
    expect(textAt(t, 3, 0)).toBe("Working Memory");
    expect(textAt(t, 3, 4)).toBe("High Average");

    // Every cell in a clean table is high confidence — no shaky reads.
    expect(t.cells.every((c) => c.confidence === "parsed_ok")).toBe(true);
    // Clean table: no merges, so every cell spans exactly one grid coordinate.
    expect(t.cells.every((c) => c.colSpan === 1 && c.rowSpan === 1)).toBe(true);
  });

  test("detects the styled heading as a semantic section", async () => {
    const ir = await parseDocx(await loadFixture("basic-score-table.docx"));
    const results = ir.sections.find((s) => s.title === "Assessment Results");
    expect(results).toBeDefined();
    expect(results!.confidence).toBe("parsed_ok");
    expect(results!.implicit).toBe(false);
  });
});

describe("awkward structure fixture", () => {
  test("(a) a cleanly-merged header resolves parsed_ok with correct addressing", async () => {
    const ir = await parseDocx(await loadFixture("awkward-structure.docx"));
    const t = ir.tables.find((x) => x.numColumns === 4)!;

    // Full-width banner: one cell spanning all four columns, unambiguous.
    const banner = cellAt(t, 0, 0);
    expect(banner.text).toBe("Cognitive Profile Composite");
    expect(banner.colSpan).toBe(4);
    expect(banner.confidence).toBe("parsed_ok");
    // Every covered coordinate points at the same banner cell.
    expect([0, 1, 2, 3].map((c) => t.grid[0]![c])).toEqual(Array(4).fill(banner.id));

    // Vertical merge: the column-0 origin carries the text, and the continuation
    // coordinate below resolves to that same origin (parsed_ok, unambiguous).
    const origin = cellAt(t, 2, 0);
    expect(origin.text).toBe("Verbal");
    expect(origin.rowSpan).toBe(2);
    expect(origin.confidence).toBe("parsed_ok");
    expect(t.grid[3]![0]).toBe(origin.id); // continuation resolves to origin
    expect(cellAt(t, 3, 0)).toBe(origin);
  });

  test("(b) an ambiguous partial merge is low-confidence on exactly the affected cell, not its neighbors", async () => {
    const ir = await parseDocx(await loadFixture("awkward-structure.docx"));
    const t = ir.tables.find((x) => x.numColumns === 4)!;

    // The partial horizontal merge over columns 2-3 needs content-to-column
    // inference -> low confidence, and it covers both coordinates.
    const merged = cellAt(t, 4, 2);
    expect(merged.text).toBe("9 (Average)");
    expect(merged.colSpan).toBe(2);
    expect(merged.confidence).toBe("parsed_low_confidence");
    expect(t.grid[4]![3]).toBe(merged.id);

    // Its row neighbors are untouched — no blanket cap on the row or table.
    expect(cellAt(t, 4, 0).confidence).toBe("parsed_ok"); // "Visual"
    expect(cellAt(t, 4, 1).confidence).toBe("parsed_ok"); // "Block Design"

    // Exactly one low-confidence cell in the whole table.
    const low = t.cells.filter((c) => c.confidence === "parsed_low_confidence");
    expect(low).toHaveLength(1);
    expect(low[0]!.id).toBe(merged.id);
  });

  test("(c) a table split across a page break rejoins with the seam marked low-confidence", async () => {
    const ir = await parseDocx(await loadFixture("awkward-structure.docx"));
    const joined = ir.tables.find((x) => x.joinedFrom.length > 1)!;

    // Rejoined from two source tables into one logical grid.
    expect(joined.joinedFrom).toEqual(["t1", "t2"]);
    expect(joined.numColumns).toBe(3);
    // Duplicated header dropped: header + two data rows, not header twice.
    expect(joined.numRows).toBe(3);
    expect([0, 1, 2].map((c) => textAt(joined, 0, c))).toEqual([
      "Area",
      "Standard Score",
      "Range",
    ]);
    expect(textAt(joined, 1, 0)).toBe("Reading");
    expect(textAt(joined, 2, 0)).toBe("Mathematics");

    // The seam is where the second source table's body begins, flagged low.
    expect(joined.seams).toHaveLength(1);
    expect(joined.seams[0]!.atRow).toBe(2);
    expect(joined.seams[0]!.confidence).toBe("parsed_low_confidence");
    // Seam propagates to the table's overall confidence.
    expect(joined.confidence).toBe("parsed_low_confidence");
  });

  test("does NOT rejoin tables when column counts differ (no false join)", async () => {
    // The 4-column awkward table and the 3-column split table are separated by a
    // heading paragraph and have different column counts — never merged.
    const ir = await parseDocx(await loadFixture("awkward-structure.docx"));
    expect(ir.tables).toHaveLength(2);
    expect(ir.tables.map((t) => t.numColumns).sort()).toEqual([3, 4]);
  });
});
